#:import MapView kivy_garden.mapview.MapView
#:import MapSource kivy_garden.mapview.MapSource
#:import MapMarker kivy_garden.mapview.MapMarker
#:import MapMarkerPopup kivy_garden.mapview.MapMarkerPopup
#:import Factory kivy.factory.Factory
#:import ButtonBehavior kivy.uix.behaviors.button
#:import StringProperty kivy.properties.StringProperty
#:import cos math.cos
#:import sin math.sin
#:import pi math.pi
#:import Singleton_Perfil Modulos.Singleton.Perfil.Singleton_Perfil

<Miniatura_Evento>: 
        # title, tiempo, action ahora son propiedades válidas de la clase Python.
    title: 'Titulo de Evento'
    tiempo: "15d"
    action: None
    
    # El popup se mostrará automáticamente al hacer clic en el marcador
    BoxLayout:
        orientation: 'vertical'
        size_hint: None, None
        size: dp(200), dp(80)
        
        # Usamos un Button en lugar de ButtonBehavior
        Button:
            size_hint: 1, 1
            background_color: 0,0,0,0  # Transparente
            on_release: 
                menu = Factory.Menu_Evento()
                menu.titulo = root.title
                menu.open()
            
            BoxLayout:
                orientation: 'vertical'
                pos: self.parent.pos
                size: self.parent.size
                
                canvas.before:
                    Color:
                        rgba: 0.2,0.6,0.1,1
                    Rectangle:
                        size: self.size
                        pos: self.pos
                        
                Label:
                    text: root.title
                    size_hint: 1, 0.5
                    
                Label:
                    text: root.tiempo
                    size_hint: 1, 0.5
                    color: 0,0,0,1
                    canvas.before:
                        Color:
                            rgba: 1,1,1,1
                        Rectangle:
                            pos: self.pos
                            size: self.size


<Menu_Evento_Imagen@BoxLayout>:
    imagen: None
    canvas.before:
        Color:
            rgba:0,0,0,1
        Rectangle: 
            size:self.size
            pos:self.pos
    Image:
        source: root.imagen
        pos: root.pos[0]+1,root.pos[1]+1
        size_hint: (None,None)
        size: root.size[0]-2,root.size[1]-2

<Elemento_Estrella@Widget>:
    radio: 50.0 
    porcentaje_visible:0
    on_size: 
        self.radio = min(self.width, self.height) * 0.45

    canvas.before:
        Color:
            rgba: 1, 0.8, 0.1, root.porcentaje_visible 
        Triangle:
            points: [self.center_x, self.center_y, self.center_x, self.center_y + self.radio, self.center_x + self.radio, self.center_y]
        Triangle:
            points: [self.center_x, self.center_y, self.center_x + self.radio, self.center_y, self.center_x, self.center_y - self.radio]
        Triangle:
            points: [self.center_x, self.center_y, self.center_x, self.center_y - self.radio, self.center_x - self.radio, self.center_y]
        Triangle:
            points: [self.center_x, self.center_y, self.center_x - self.radio, self.center_y, self.center_x, self.center_y + self.radio]


<Etiqueta_Evento@BoxLayout>:
    texto: 'Sin Texto'
    size_hint: (1,None)
    
    height: dp(25)
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            size: self.size
            pos:self.pos
            radius: [dp(5)]
        Color:
            rgba: 1,1,1,1
        RoundedRectangle:
            size: self.size[0]-2,self.size[1]-2
            pos:self.pos[0]+1,self.pos[1]+1
            radius: [dp(5)]
    Label:
        text: root.texto
        font_size: self.height*0.8
        size_hint: (1,1)
        color: (0,0,0,1)



<Menu_Evento_Informacion@BoxLayout>:
    titulo: 'Sin Titulo'
    texto: "Sin Texto"
    calificacion: 0
    ubicacion: ''
    size_hint_y: None
    orientation: 'vertical'
    height: self.minimum_height
    padding: dp(5)
    canvas.before:
        Color:
            rgba: 0,0,0,1
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size: self.size[0]-2,self.size[1]-2
            pos: self.pos[0]+1,self.pos[1]+1

        
    Label:
        size_hint: (1,None)
        height: dp(40)
        font_size: self.height*0.8
        color: (0,0,0,1)
        text: root.titulo
    TextInput:
        size_hint: (1,None)
        height: self.minimum_height
        hint_text: "Escribe una descripción"
        multiline: True
        text: root.texto
        background_disabled_normal: ''
        disabled: True if Singleton_Perfil.get_instance().tipo_perfil != 'Organizador' else False
    Label:
        text: root.ubicacion
        size_hint: (1,None)
        height: dp(50)
        font_size: ((self.width/len(self.text))*2) if self.width and self.text else self.height*0.6
        text_size: (self.width,None)
        
        color: (0,0,0,1)
        canvas.before:
            Color:
                rgba: (1,1,0.9,1)
            Rectangle:
                pos: self.pos
                size:self.size

    BoxLayout:
        orientation: 'horizontal'
        size_hint: (1,None)
        height: dp(35)
        Label:
            text: 'Calificación'
            font_size: self.height*0.8
            color: (0,0,0,1)
        Label:
            text: f'{root.calificacion}/5'
            font_size: self.height*0.8
            size_hint: (None,1)
            color: (0,0,0,1)
    BoxLayout:
        orientation: 'horizontal'
        size_hint: (None,None)
        width: self.minimum_width
        height: dp(50)
        pos_hint: {'center_x':0.5}
        Elemento_Estrella:
            size_hint: (None, 0.9)
            width: self.height
            porcentaje_visible: 1 if root.calificacion >= 1 else (root.calificacion - int(root.calificacion) if int(root.calificacion) == 0 else 0)
        Elemento_Estrella:
            size_hint: (None, 0.9)
            width: self.height
            porcentaje_visible: 1 if root.calificacion >= 2 else (root.calificacion - int(root.calificacion) if int(root.calificacion) == 1 else 0)
        Elemento_Estrella:
            size_hint: (None, 0.9)
            width: self.height
            porcentaje_visible: 1 if root.calificacion >= 3 else (root.calificacion - int(root.calificacion) if int(root.calificacion) == 2 else 0)
        Elemento_Estrella:
            size_hint: (None, 0.9)
            width: self.height
            porcentaje_visible: 1 if root.calificacion >= 4 else (root.calificacion - int(root.calificacion) if int(root.calificacion) == 3 else 0)
        Elemento_Estrella:
            size_hint: (None, 0.9)
            width: self.height
            porcentaje_visible: 1 if root.calificacion >= 5 else (root.calificacion - int(root.calificacion) if int(root.calificacion) == 4 else 0)
    
    Label:
        size_hint: (1,None)
        height: dp(35)
        text: 'Etiquetas'
        font_size: self.height*0.8
        color: 0,0,0,1
        canvas.before:
            Color:
                rgba: 0,0,0,1
            RoundedRectangle:
                size: self.size
                pos:self.pos
                radius: [dp(5)]
            Color:
                rgba:1,1,1,1
            RoundedRectangle:
                size: self.size[0]-2,self.size[1]-2
                pos: self.pos[0]+1,self.pos[1]+1
    BoxLayout:
        id: lista_etiquetas
        orientation: 'vertical'
        size_hint: (0.8,None)
        pos_hint: {'center_x':0.5}
        height: self.minimum_height


                        
<Menu_Evento_ListaCompra@BoxLayout>:
    orientation: 'vertical'
    pos_hint: {'center_x':0.5}
    size_hint: (1,1)
    Button:
        text: 'Comprar Entradas'
        size_hint: (1,None)
        height: dp(35)
        color: (0,0,0,1)
    Button:
        text: 'Comprar Pre-Inscripción'
        size_hint: (1,None)
        height: dp(35)
        color: (0,0,0,1)
    Button:
        text: 'Compras con Cupones'
        size_hint: (1,None)
        height: dp(35)
        color: (0,0,0,1)
                    
                


         
        



<Menu_Evento>:
    size_hint: 0.99, 0.9
    padding: dp(5)
    pos_hint: {'center_y':0.5}
    background_color: (1,1,1,0)
    auto_dismiss: True
    pestana:'imagen'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(50)
            canvas.before:
                Color:
                    rgba:1,1,1,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            
            Button:
                text: 'Fijar'
                color: (0,0,0,1)
                background_color: (0.5,0.5,0.5,1)
                background_normal: ''
                background_down: ''
                size_hint_x: None
                width: self.height
                #on_release: root.dismiss() if root.dismiss else None
            Button:
                text: 'Compartir'
                color: (0,0,0,1)
                background_color: (0.2,0.2,0.9,1)
                background_normal: ''
                background_down: ''
                size_hint_x: None
                width: self.height
                #on_release: root.dismiss() if root.dismiss else None
            Label:
                text: root.titulo
                color: (0,0,0,1)
                font_size: self.height * 0.4
                valign: 'center'
                halign: 'center'
            Button:
                text: 'X'
                color: (0,0,0,1)
                background_color: (0.9,0.2,0.2,1)
                background_normal: ''
                background_down: ''
                size_hint_x: None
                width: self.height
                on_release: root.dismiss() if root.dismiss else None
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1,1)
            canvas.before:
                Color:
                    rgba: 1,0.95,0.95,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            ScrollView:
                
                id: listado_menu_evento
                do_scroll_x: False
                do_scroll_y: True
                scroll_y: 1
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: self.minimum_height
                    spacing: dp(2)
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        color: (0,0,0,1)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        color: (0,0,0,1)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        color: (0,0,0,1)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        color: (0,0,0,1)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        color: (0,0,0,1)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                    Label:
                        text: 'Hola'
                        font_size: dp(30)
                        color: (0,0,0,1)
                        size_hint_y: None
                        height: self.font_size+dp(5)
                        canvas.before:
                            Color: 
                                rgba: 1,1,0,1
                            Rectangle:
                                size: self.size
                                pos: self.pos 
                        

        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(60)
            spacing: dp(3)
            canvas.before:
                Color: 
                    rgba: 1,1,1,1
                Rectangle:
                    size: self.size
                    pos: self.pos
            Button:
                text: 'Info'
                background_down: ''
                #background_normal: ''
                background_color: (0.1,0.4,1,1)
                size_hint_x: 0.3
                on_release: root.Cargar_Interfaz_Informacion() if root.pestana != 'info' else root.Cargar_Interfaz_Imagenes(); root.pestana="info" if root.pestana != 'info' else  'imagen'
            Button:
                text: 'Shop'
                background_down: ''
                #background_normal: ''
                background_color: (0,0,1,1)
                size_hint_x: 0.3
                on_release: root.Cargar_Interfaz_ListaCompras() if root.pestana != 'shop' else root.Cargar_Interfaz_Imagenes(); root.pestana="shop" if root.pestana != 'shop' else  'imagen'
            Button:
                text: 'Alert'
                background_down: ''
                #background_normal: ''
                background_color: (0.1,0.1,0,1)
                size_hint_x: 0.3


<AgregarMapa@MapView>:
    id: map_view
    lat: -33.4569400  # Usar un valor fijo o la propiedad del Layout_Mapa
    lon: -70.6482700
    zoom: 12
    zoom_min: 4
    zoom_max: 18
    map_source: MapSource(url="https://tile.openstreetmap.org/{z}/{x}/{y}.png",cache_key="custom_map",min_zoom=4,max_zoom=18,tile_size=256,image_ext="png")
    on_parent:
        self._marker = None
    on_lat:
        # CORRECCIÓN: Usar root.parent.parent para llegar al Layout_Mapa
        if root.parent.parent.ubicacion_actualizada and hasattr(self, '_marker'): [ \
        self.remove_marker(self._marker) if self._marker else None, \
        
        # 💥 CAMBIO CRÍTICO AQUÍ 💥
        # Usar Miniatura_Evento en lugar de MapMarker para el marcador de la ubicación actual
        setattr(self, '_marker', Factory.Miniatura_Evento(lat=root.parent.parent.latitud, lon=root.parent.parent.longitud, title="Ubicación Actual")), \
        
        self.add_marker(self._marker), \
        
        setattr(root.parent.parent, 'marker', self._marker) \
        ]



<Layout_Mapa>:
    BoxLayout:
        id: mapa
        size_hint: (1,1)
            

    BoxLayout:
        orientation: 'horizontal'
        size_hint: (1,None)
        height: dp(50)
        pos_hint: {"top":1}
        Button:
            text: 'Atras'
            size_hint_x: 0.2
            on_release: root.Regresar_Estandar()
        TextInput:
            size_hint_x: 0.8

