#: import Factory kivy.factory.Factory

<Input_CreacionEventos_Nombre@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'vertical'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]
        
    TextInput:
        id: usuario
        hint_text: root.t_text
        
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False




<Input_CreacionEventos_Descripcion@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    # 💥 CAMBIO CLAVE: Cambiar a vertical
    orientation: 'vertical' 
    padding: dp(10)
    size_hint_y: None
    height: self.minimum_height
    canvas.before:
        # ... (Tu código de canvas se mantiene igual)
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]
        
    TextInput:
        id: usuario
        size_hint: (1,None)
        hint_text: "Escribe una descripción"
        multiline: True
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        write_tab: False



<Input_CreacionEventos_Ubicacion@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    password: False
    orientation: 'vertical'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]
        
    TextInput:
        id: usuario
        hint_text: root.t_text
        multiline: True
        
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False
        password: root.password
        

<Input_CreacionEventos_Fecha@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'horizontal'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]
        
    TextInput:
        id: usuario
        hint_text: root.t_text
        multiline: True
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False


<Input_CreacionEventos_Hora@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'horizontal'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]

    TextInput:
        id: usuario
        hint_text: root.t_text
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False

<Input_CreacionEventos_dinero@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'horizontal'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]

    TextInput:
        id: dinero
        hint_text: root.t_text
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False



<Input_CreacionEventos_numero@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'horizontal'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]

    TextInput:
        id: usuario
        hint_text: root.t_text
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False


<Input_CreacionEventos_rut@BoxLayout>:
    bg_icon: 0.7,0.1,0.7,1
    bg_text: 1,1,1,1
    t_text: 'Sin Texto'
    orientation: 'horizontal'
    pos_hint: {'center_y': 0.5}
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [20]
        Color:
            rgba: root.bg_text
        RoundedRectangle: #fondo blanco
            pos: self.pos[0] + dp(2), self.pos[1] + dp(2)
            size: self.size[0] - dp(4), self.size[1] - dp(4)
            radius: [20]

    TextInput:
        id: rut
        hint_text: root.t_text
        font_size: root.size[1]*0.4
        size_hint: 0.8,0.9
        foreground_color: 0,0,0,1
        background_color: 1,1,1,0
        cursor_color: 0,0,0,1
        pos_hint: {'center_y': 0.5}
        padding: (dp(10),((self.height - self.font_size)/2)-dp(2),dp(15),((self.height - self.font_size)/2)-dp(2))
        write_tab: False


<Alertas_Mensaje@ModalView>:
    titulo: 'Sin Titulo'
    contenido: 'Sin Contenido'
    bg: (1,0,0,1)
    size_hint: (0.9,0.7)
    canvas.before:
        Color:
            rgba: 0,0,0,1
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [dp(10)]
        Color:
            rgba: root.bg
        RoundedRectangle:
            size: self.size[0]-2, self.size[1]-2
            pos: self.x+1,self.y+1
            radius: [dp(10)]
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.titulo
            size_hint_y: None
            height: dp(30)
            font_size: self.height*0.7
            color: 1,1,1,1
            canvas.before:
                Color:
                    rgba: 0,0,0,1
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [dp(10),0,dp(10),0]

        Label:
            text: root.contenido
            font_size: dp(18)
            size_hint: 0.9,0.9
            text_size: (self.width,None)
            padding: dp(30)

        Button:
            text: 'Cerrar Mensaje'
            color: 1,1,1,1
            size_hint: 0.8,None
            pos_hint: {'center_x':0.5}
            padding: dp(30)
            height: dp(30)
            background_color: (0.3,0.3,0.7,1)
            on_release: root.dismiss()


<Etiquetas_Elementos@BoxLayout>:
    orientation: 'horizontal'
    size_hint_y: None
    text: 'Sin Texto'
    height: dp(30)
    padding: dp(5)
    canvas.before:
        Color: 
            rgba: 0.7,0.7,0.7,1
        Line: 
            points: self.x,self.y,self.x+self.width,self.y
    CheckBox:
        id: seleccion
        active: False
        size_hint: None, 0.9
        width: self.height
        pos_hint: {'center_y': 0.5}
        background_checkbox_down: ''
        background_checkbox_disabled_down: ''
        background_radio_down: ''
        
        canvas: 
            Color:
                rgba: (0, 0, 0, 1) if self.active else (0.7, 0.7, 0.7, 1)
            Ellipse:
                pos: self.pos
                size: self.size
    Label:
        text: root.text
        font_size: root.height*0.7
        color: 0,0,0,1

<Lista_Etiquetas_CreacionEventos@BoxLayout>:
    orientation: 'vertical'
    size_hint: (1,None)
    padding: dp(5)
    height: self.minimum_height
    canvas.before:
        Color: 
            rgba: 0,0,0,1
        RoundedRectangle: 
            size: self.size
            pos: self.pos
            radius: [dp(5)]
        Color: 
            rgba: 1,1,1,1
        RoundedRectangle: 
            size: self.width-2,self.height-2
            pos: self.x+1,self.y+2
            radius: [dp(5)]
    GridLayout:
        id: Elementos
        cols: 1
        size_hint_y: None
        height: self.minimum_height
        Etiquetas_Elementos:
            id:0
            text: 'Música'
        Etiquetas_Elementos:
            id:1
            text: 'Deportes'
        Etiquetas_Elementos:
            id:2
            text: 'Arte'
        Etiquetas_Elementos:
            id:3
            text: 'Tecnología'
        Etiquetas_Elementos:
            id:4
            text: 'Comida'
        Etiquetas_Elementos:
            id:5
            text: 'Educación'
        Etiquetas_Elementos:
            id:6
            text: 'Negocios'
        Etiquetas_Elementos:
            id:7
            text: 'Entretenimiento'
        Etiquetas_Elementos:
            id:8
            text: 'Salud'
        Etiquetas_Elementos:
            id:9
            text: 'Cine'
        Etiquetas_Elementos:
            id:10
            text: 'Escolar'
        Etiquetas_Elementos:
            id:11
            text: 'Formal'
        Etiquetas_Elementos:
            id:12
            text: 'Informal'
        Etiquetas_Elementos:
            id:13
            text: 'Familiar'
        Etiquetas_Elementos:
            id:14
            text: 'Jovenes'
        Etiquetas_Elementos:
            id:15
            text: 'Adultos'


<Fechas_ListaInvitados@BoxLayout>:
    orientation: 'vertical'
    size_hint_y: None
    height: dp(155)
    spacing: dp(5)
    canvas.before:
        Color: 
            rgba: 0,0,0,1
        RoundedRectangle: 
            size: self.size
            pos: self.pos
            radius: [dp(5)]
        Color: 
            rgba: 1,1,1,1
        RoundedRectangle: 
            size: self.width-2,self.height-2
            pos: self.x+1,self.y+2
            radius: [dp(5)]
    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: dp(65)
        spacing: dp(2)
        Input_CreacionEventos_Fecha:
            id: fecha_inicio
            t_text: "Fecha Inicia"
            multiline: False
            font_size: dp(14)
            size_hint: (1, None)
            height: dp(30)
        Input_CreacionEventos_Hora:
            id: hora_inicio
            t_text: "Hora Inicia"
            size_hint: (1, None)
            height: dp(30)

    BoxLayout:
        orientation: 'vertical'
        size_hint_y: None
        height: dp(65)
        spacing: dp(2)
        Input_CreacionEventos_Fecha:
            id: fecha_fin
            t_text: "Fecha Termina"
            multiline: False
            font_size: dp(14)
            size_hint: (1, None)
            height: dp(30)
        Input_CreacionEventos_Hora:
            id: hora_fin
            t_text: "Hora Termina"
            size_hint: (1, None)
            height: dp(30)
    Button:
        text: "X"
        font_size: self.height*0.4
        size_hint: (1,None)
        height: dp(20)
        background_color: (1,0,0,1)
        on_release: root.parent.remove_widget(root)

<Filas_ListaInvitados@BoxLayout>:
    orientation: 'horizontal'
    size_hint_y: None
    height: self.minimum_height
    spacing: dp(10)
    accion: None
    canvas.before: 
        Color:
            rgba: 1,1,1,1
        Rectangle:
            size:self.size
            pos:self.pos
    BoxLayout:
        orientation: 'vertical'
        size_hint: (0.5,None)
        pos_hint: {'top':1}      
        Input_CreacionEventos_rut:
            id: rut_invitado
            t_text: "Ingresar Rut"
            font_size: self.height*0.4
            color: 0,0,0,1
            pos_hint: {'top':1}
            size_hint: (1,None)
            height: dp(30)
            background_disabled_normal: ''
            
        Button:
            text: 'X'
            font_size: self.height*0.5
            size_hint: (1,None)
            height: dp(30)
            color: (1,1,1,1)
            background_color: (1,0,0,1)
            on_release:
                root.parent.remove_widget(root)
    BoxLayout:
        orientation: 'vertical'
        size_hint: (0.5,None)
        height: self.minimum_height
        BoxLayout:
            id: fechas_invitado
            orientation: 'vertical'
            size_hint: (1,None)
            height: self.minimum_height
            pos_hint: {'center_y': 0.5}
            spacing: dp(3)
        BoxLayout:
            orientation: 'vertical'
            size_hint: (1,None)
            height: dp(30)
            width: dp(30)
            Button:
                text: '+'
                font_size: self.height*0.8
                size_hint: (1,None)
                height: dp(30)
                background_color: (0,0.6,0,1)
                on_release: root.accion(root) if root.accion else None
            

<Tabla_Invitados@BoxLayout>:
    orientation: 'vertical'
    size_hint_y: None
    height: self.minimum_height
    canvas.before:
        Color:
            rgba: 0.8,0.8,0.8,1
        Rectangle:
            size:self.size
            pos:self.pos
    BoxLayout:
        orientation: 'vertical'
        size_hint: (1,None)
        height: self.minimum_height
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1,None)
            height: self.minimum_height
            padding: [dp(10),dp(5),dp(10),dp(5)]
            canvas: 
                Color:
                    rgba: 0.2,0.6,0.1,1
                Rectangle:
                    size:self.size
                    pos:self.pos
            Label:
                text: 'Lista de Invitados'
                font_size: self.height*0.6
                color: 0,0,0,1
                size_hint: (0.65,None)
                height: dp(30)
                pos_hint: {'center_y':0.5}
                valign: 'center'
                halign: 'center'

            BoxLayout:
                orientation: 'vertical'
                size_hint: (0.35,None)
                height: self.minimum_height
                Button:
                    id: btn_importar
                    text: 'Importar'
                    font_size: self.height*0.5
                    size_hint: (1,None)
                    height: dp(30)
                    background_color: (0,0.6,0,1)
                    on_release: root.seleccionar_archivo('xlsx')#root.Importar_invitados()


                Button:
                    text: 'Borrar Todo'
                    font_size: self.height*0.5
                    size_hint: (1,None)
                    color: (1,1,1,1)
                    height: dp(30)
                    background_color: (1,0,0,1)
                    on_release: filas_invitados.clear_widgets()
        BoxLayout:
            orientation: 'horizontal'
            size_hint_y: None
            height: dp(30)
            Label:
                text: 'Rut'
                font_size: (self.height*0.5)
                color: 0,0,0,1
                size_hint: (0.25,None)
                height: dp(30)
            Label:
                text: 'Fechas de Invitación'
                font_size: self.height*0.5
                color: 0,0,0,1
                size_hint: (0.75,None)
                height: dp(30)
    BoxLayout:
        orientation: 'vertical'
        size_hint: (1,None)
        height: self.minimum_height
        BoxLayout:
            id: filas_invitados
            orientation: 'vertical'
            size_hint: (1,None)
            height: self.minimum_height
            spacing: dp(10)
        BoxLayout:
            orientation: 'horizontal'
            size_hint: (1,None)
            height: dp(50)
            Button:
                text: '+'
                size_hint: (1,None)
                height: dp(40)
                font_size: self.height*0.8
                background_color: (0,0.6,0,1)
                on_release: root.Agregar_invitado()

    
        
    





<Layout_CreacionEventos>:
    orientation: 'vertical'
    size_hint: (1,1)
    canvas.before:
        Color:
            rgba:1,1,1,1
        Rectangle:
            size:self.size
            pos:self.pos
    BoxLayout:
        orientation: 'horizontal'
        size_hint: (1,None)
        height: dp(50)
        Button:
            text: 'Atras'
            size_hint: (0.25,1)
            on_release: root.Abrir_MenuPrincipal() if Singleton_Perfil.get_instance().tipo_perfil else Abrir_Login()
        Label:
            text: 'Crear Evento'
            color:0,0,0,1
            font_size: self.height*0.4
            size_hint: (0.65,1)
        Button:
            text:'Crear'
            color: (1,1,1,1)
            background_color: (0.2,0.5,0.2)
            size_hint: (0.25,1)
            on_release: root.Crear_Evento(); print('Se presiona')
    
    BoxLayout:
        orientation: 'vertical'
        size: (1,1)
        padding: [dp(10),dp(10)]
        canvas.before:
            Color: 
                rgba: 1,0.95,0,1
            Rectangle:
                size: self.size
                pos: self.pos
        ScrollView:
            do_scroll_x: False
            do_scroll_y: True
            scroll_y: 1
            size_hint: (1,1)
            BoxLayout:
                id: contenedor
                orientation: 'vertical'
                size_hint: (1,None)
                pos_hint: {'top':1}
                height: self.minimum_height
                spacing: dp(20)
                Input_CreacionEventos_Nombre:
                    id: NombreEvento
                    t_text: 'Nombre del Evento'
                    size_hint_y: None
                    height: dp(40)

                Input_CreacionEventos_Descripcion:
                    id: Descripcion
                    t_text: 'Descripción del Evento'
                    size_hint_y: None
                    
                Input_CreacionEventos_Ubicacion:
                    id: Ubicacion
                    t_text: 'Ubicación'
                    password: False
                    size_hint_y: None
                    height: dp(40)

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint_y: None
                    height: dp(40)
                    Input_CreacionEventos_numero:
                        id: Latitud
                        t_text: 'Latitud'
                        size_hint_x: 0.5
                    Input_CreacionEventos_numero:
                        id: Longitud
                        t_text: 'Longitud'
                        size_hint_x: 0.5

                Input_CreacionEventos_Fecha:
                    id: FechaInicio
                    t_text: 'Fecha Inicia'
                    password: False
                    size_hint_y: None
                    height: dp(40)
                Input_CreacionEventos_Fecha:
                    id: FechaFin
                    t_text: 'Fecha Finaliza'
                    password: False
                    size_hint_y: None
                    height: dp(40)
                Input_CreacionEventos_Hora:
                    id: HoraInicio
                    t_text: 'Hora Inicia'
                    password: False
                    size_hint_y: None
                    height: dp(40)
                Input_CreacionEventos_Hora:
                    id: HoraFin
                    t_text: 'Hora Finaliza'
                    password: False
                    size_hint_y: None
                    height: dp(40)
                Label:
                    text: 'Etiquetas'
                    font_size: dp(18)
                    color: (0,0,0,1)
                    size_hint_x: None
                Lista_Etiquetas_CreacionEventos:
                    id: Lista_Etiquetas
                BoxLayout:
                    orientation: 'horizontal'
                    size_hint: (1,None)
                    height: self.minimum_height
                    Label:
                        text: 'Valor acceso'
                        color: (0,0,0,1)
                        size_hint: (0.3,None)
                        height: dp(35)
                        font_size: self.width/len(self.text)*1.7
                        valign: 'center'
                        halign: 'center'

                        canvas.before:
                            Color: 
                                rgba: 0.2,0.6,0.1,1
                            Rectangle:
                                size:self.size
                                pos:self.pos 
                         
                    Spinner:
                        id: acceso_spinner
                        values: ['Paga','Gratis']
                        size_hint_x: 0.3 if root.ids.acceso_spinner.text=='Paga' else 0.7
                        size_hint_y: None
                        height: dp(35)
                        font_size: self.height*0.6
                        background_color: 0.2, 0.6, 1, 1 # Color del botón principal
                        color: 1, 1, 1, 1 # Color del texto del botón principal
                Input_CreacionEventos_dinero:
                    id: entrada_precio
                    t_text: 'Precio de Entrada'
                    size_hint_y: None
                    size_hint_x: 1 if root.ids.acceso_spinner.text=='Paga' else 0
                    #width: 0 if root.ids.acceso_spinner.text=='Paga' else None
                    height: dp(40) if root.ids.acceso_spinner.text=='Paga' else 0
                    opacity: 1 if root.ids.acceso_spinner.text=='Paga' else 0
                    disabled: True if root.ids.acceso_spinner.text=='Gratis' else False

                BoxLayout:
                    orientation: 'horizontal'
                    size_hint: (1,None)
                    height: self.minimum_height
                    Label:
                        text: 'Tipo Evento'
                        color: (0,0,0,1)
                        height: dp(30)
                        font_size: self.width/len(self.text)*1.9
                        size_hint: (0.3,None)
                        valign: 'center'
                        halign: 'center'

                        canvas.before:
                            Color: 
                                rgba: 0.2,0.6,0.1,1
                            Rectangle:
                                size:self.size
                                pos:self.pos 
                         
                    Spinner:
                        id: visibilidad_spinner
                        values: ['Publico','Privado']
                        size_hint_x: 0.3 if root.ids.visibilidad_spinner.text=='Publico' else 0.7
                        size_hint_y: None
                        height: dp(30)
                        font_size: self.height*0.6
                        background_color: 0.2, 0.6, 1, 1 # Color del botón principal
                        color: 1, 1, 1, 1 # Color del texto del botón principal
                        on_text: root.Agregar_TablaInvitados()
                        #opacity: 1 if root.ids.visibilidad_spinner.text!='Publico' else 0
                Input_CreacionEventos_dinero:
                    id: preinscripcion_precio
                    t_text: 'Precio de la pre-inscripción'
                    password: False
                    size_hint_y: None
                    size_hint_x: 1 if root.ids.visibilidad_spinner.text=='Publico' else 0
                    #width: 0 if root.ids.acceso_spinner.text=='Paga' else None
                    height: dp(40) if root.ids.visibilidad_spinner.text=='Publico' else 0
                    opacity: 1 if root.ids.visibilidad_spinner.text=='Publico' else 0
                    disabled: True if root.ids.visibilidad_spinner.text=='Privado' else False


                     
                    
                
                    
                

                         






